CREATE TABLE CUSTOMERS(
    PHONENUMBER VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    PASSWORD1 VARCHAR(100) NOT NULL
);

CREATE TABLE MANAGER(
    PHONENUMBER VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    PASSWORD1 VARCHAR(100) NOT NULL
);

/*DROP TABLE PRODUCT*/

CREATE TABLE STORE(
    NUMBER VARCHAR(100) PRIMARY KEY,
    LOCATION VARCHAR(100) NOT NULL,
    ZIPCODE VARCHAR(5) NOT NULL,
    MANAGERPHONE VARCHAR(10) FOREIGN KEY REFERENCES MANAGER(PHONENUMBER) NOT NULL
);

CREATE TABLE CUSTOMERORDER(
    ID INT PRIMARY KEY,
    TOTAL DECIMAL(10,2) NOT NULL,
    CUSTOMERPHONE VARCHAR(10) FOREIGN KEY REFERENCES CUSTOMERS(PHONENUMBER) NOT NULL,
    STOREID VARCHAR(100) FOREIGN KEY REFERENCES STORE(NUMBER) NOT NULL,
);


CREATE TABLE PRODUCTS(
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(100) NOT NULL,
    STOCK INT NOT NULL,
    UNITPRICE DECIMAL(10,2) NOT NULL,
    STOREID VARCHAR(100) FOREIGN KEY REFERENCES STORE(NUMBER) NOT NULL,
);

CREATE TABLE LINEITEM(
    ID INT PRIMARY KEY IDENTITY(1,1),
    QUANTITY INT NOT NULL,
    COST INT NOT NULL,
    UNITPRICE DECIMAL(10,2) NOT NULL,
    ORDERID INT FOREIGN KEY REFERENCES CUSTOMERORDER(ID) NOT NULL,
    PRODUCTID INT FOREIGN KEY REFERENCES PRODUCTS(ID) NOT NULL
);

CREATE TABLE STOREPRODUCTS(
    ID INT PRIMARY KEY IDENTITY(1,1),
    STOREID VARCHAR(100) FOREIGN KEY REFERENCES STORE(NUMBER) NOT NULL,
    PRODUCTID INT FOREIGN KEY REFERENCES PRODUCTS(ID) NOT NULL
);

INSERT INTO MANAGER VALUES('7819754881', 'Peterclaver', '1234', '1234');

SELECT * FROM MANAGER;